In [1]:
import pandas as pd
import sys
import os

In [17]:
df = pd.read_csv("C:/Users/saura/OneDrive/Desktop/sql/Basics/Pincode.csv", sep=",")

In [18]:
df.head()

,officename,pincode,officeType,Deliverystatus,divisionname,regionname,circlename,Taluk,Districtname,statename
0,Ada B.O,504293,B.O,Delivery,Adilabad,Hyderabad,Andhra Pradesh,Asifabad,Adilabad,ANDHRA PRADESH
1,Andugulpet B.O,504231,B.O,Delivery,Adilabad,Hyderabad,Andhra Pradesh,Luxettipet,Adilabad,ANDHRA PRADESH
2,Annaram B.O,504201,B.O,Delivery,Adilabad,Hyderabad,Andhra Pradesh,Chennur,Adilabad,ANDHRA PRADESH
3,Arli (T) B.O,504312,B.O,Delivery,Adilabad,Hyderabad,Andhra Pradesh,Adilabad,Adilabad,ANDHRA PRADESH
4,Bambara B.O,504295,B.O,Delivery,Adilabad,Hyderabad,Andhra Pradesh,Asifabad,Adilabad,ANDHRA PRADESH

In [4]:
df.columns

Index(['officename', 'pincode', 'officeType', 'Deliverystatus', 'divisionname',
       'regionname', 'circlename', 'Taluk', 'Districtname', 'statename'],
      dtype='object')

In [7]:
df[df['statename']=="BIHAR"]

,officename,pincode,officeType,Deliverystatus,divisionname,regionname,circlename,Taluk,Districtname,statename
20177,Ahiyapur B.O,851111,B.O,Delivery,Begusarai,Muzaffarpur,Bihar,Begusarai,Begusarai,BIHAR
20178,Akopur B.O,848202,B.O,Delivery,Begusarai,Muzaffarpur,Bihar,Begusarai,Begusarai,BIHAR
20179,Amba B.O,851112,B.O,Delivery,Begusarai,Muzaffarpur,Bihar,Begusarai,Begusarai,BIHAR
20180,Badalpura B.O,851129,B.O,Delivery,Begusarai,Muzaffarpur,Bihar,Begusarai H.o,Begusarai,BIHAR
20181,Begusarai Court S.O,851101,S.O,Non-Delivery,Begusarai,Muzaffarpur,Bihar,Begusarai,Begusarai,BIHAR
...,...,...,...,...,...,...,...,...,...,...
29231,Rampur Shyamchand B.O,844508,B.O,Delivery,Vaishali,Patna HQ,Bihar,Raghopur,Vaishali,BIHAR
29232,Rasulpur Enayat B.O,844114,B.O,Delivery,Vaishali,Patna HQ,Bihar,Bhagwanpur,Vaishali,BIHAR
29233,Rasulpur Purusottam B.O,844505,B.O,Delivery,Vaishali,Patna HQ,Bihar,Jandaha,Vaishali,BIHAR
29234,Sarai Dhanesh B.O,844509,B.O,Delivery,Vaishali,Patna HQ,Bihar,Sahdei Buzurg,Vaishali,BIHAR
29235,Yusufpur S.O,844101,S.O,Non-Delivery,Vaishali,Patna HQ,Bihar,Hajipur,Vaishali,BIHAR

In [19]:
df.drop([ "officeType", "Deliverystatus", "circlename"], axis=1, inplace=True)

In [20]:
df.head()
import openpyxl

In [21]:
df.to_excel("pincode_add.xlsx")